fix build breakage when HAVE_PRE_KITKAT_AUDIO_BLOB is set
if the flag is set, return INVALID_OPERATION rather than removing
the whole function.
else we will get build breakages like

undefined reference to
    'android::AudioStreamOutSink::getTimestamp(AudioTimestamp&)'

Change-Id: I0646c6e4af824bc027c800b1e7c85533cfcc1265